// Prints the SQL that checks src/lib/defaults.ts against the database (D33). Run its output with
// execute_sql: it ends in rollback, raises on the first difference and returns 'defaults ok'.
//   bun --bun scripts/defaults-assert.ts > defaults_assert.sql
import { DEFAULTS } from "../src/lib/defaults";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const d = DEFAULTS;
const channel = "c0000000-0000-4000-8000-00000000000d";
const expected = { ...d.settings, ...Object.fromEntries(Object.entries(d.commands).map(([k, v]) => [`${k}_command`, v])) };

const limits = Object.entries(d.limits)
  .map(([col, [lo, hi]]) => `  perform pg_temp.bounds(${q(col)}, ${lo}, ${hi});`)
  .join("\n");

const r = d.respect;
// A sanction's deduction at age `days` as the Nth (0-based) offence, for the expected respect.
const share = (days: number) => (r.decay.find(([n]) => days >= n)?.[1] ?? 1);
const factor = (i: number) => r.repeat[Math.min(i, r.repeat.length - 1)];
const after = (...hits: number[]) => Math.max(0, Math.min(r.start, Math.round(r.start - hits.reduce((a, b) => a + b, 0))));
const respect = [
  // name, sanctions as [kind, days ago], expected
  ["qa_warn", [["warn", 0]], after(r.warn)],
  ["qa_punish", [["punish", 0]], after(r.punish)],
  ["qa_ban", [["ban", 0]], after(r.ban)],
  ["qa_old", [["punish", 8]], after(r.punish * share(8))],
  ["qa_older", [["punish", 15]], after(r.punish * share(15))],
  ["qa_oldest", [["punish", 31]], after(r.punish * share(31))],
  ["qa_third", [["warn", 0], ["warn", 0], ["warn", 0]], after(r.warn * factor(0), r.warn * factor(1), r.warn * factor(2))],
] as const;
const rows = respect
  .flatMap(([name, list]) =>
    list.map(([kind, days], i) =>
      `  ('${channel}', ${q(name)}, ${q(kind)}, ${kind === "warn" ? 1 : "null"}, ${kind === "punish" ? 1 : "null"}, now() - interval '${days} days' - interval '${list.length - i} seconds', 'fixture')`,
    ),
  )
  .join(",\n");
const checks = respect
  .map(([name, , want]) => `  perform pg_temp.eq('respect ' || ${q(name)}, private.respect('${channel}', ${q(name)})::text, '${want}');`)
  .join("\n");

// private.retention() is a cron job, so its periods are read from its source.
const k = d.retention;
const retention = [
  `undo is not null and created_at < now() - interval '${k.undoMinutes} minutes'`,
  `delete from public.activity where created_at < now() - interval '${k.historyDays} days'`,
  `delete from public.riot_cache where fetched_at < now() - interval '${k.rankDays} days'`,
  `coalesce(last_seen_at, created_at) < now() - interval '${k.badgeDays} days'`,
]
  .map((s) => `  if strpos(pg_get_functiondef('private.retention()'::regprocedure), ${q(s)}) = 0 then raise exception 'defaults: retention() does not say %', ${q(s)} using errcode = 'XX000'; end if;`)
  .join("\n");

console.log(`-- Generated by scripts/defaults-assert.ts from src/lib/defaults.ts. Do not edit.
begin;

create function pg_temp.eq(p_what text, p_got text, p_want text) returns void
language plpgsql as $$
begin
  if p_got is distinct from p_want then
    raise exception 'defaults: % is %, DEFAULTS says %', p_what, p_got, p_want using errcode = 'XX000';
  end if;
end $$;

-- lo and hi save; lo - 1 and hi + 1 break the column's check.
create function pg_temp.bounds(p_col text, p_lo int, p_hi int) returns void
language plpgsql as $$
declare
  v int;
begin
  foreach v in array array[p_lo, p_hi] loop
    execute format('update public.settings set %I = %s where channel_id = %L', p_col, v, ${q(channel)});
  end loop;
  foreach v in array array[p_lo - 1, p_hi + 1] loop
    begin
      execute format('update public.settings set %I = %s where channel_id = %L', p_col, v, ${q(channel)});
      raise exception 'defaults: % = % saved, DEFAULTS says % to %', p_col, v, p_lo, p_hi using errcode = 'XX000';
    exception when check_violation then null;
    end;
  end loop;
  execute format('update public.settings set %I = default where channel_id = %L', p_col, ${q(channel)});
end $$;

insert into public.channels (id, kick_channel_id, slug, display_name) values ('${channel}', -1301, 'qa-defaults', 'qa defaults');
insert into public.settings (channel_id) values ('${channel}');
insert into public.moderation (channel_id, kick_username, kind, level, games_left, created_at, reason) values
${rows};

do $$
declare
  s jsonb := (select to_jsonb(x) from public.settings x where x.channel_id = ${q(channel)});
  k text;
  v jsonb;
begin
  for k, v in select * from jsonb_each(${q(JSON.stringify(expected))}::jsonb) loop
    perform pg_temp.eq(k, (s -> k)::text, v::text);
  end loop;
${limits}
  update public.settings set join_command = ${q("!" + "x".repeat(d.commandMax))} where channel_id = ${q(channel)};
  begin
    update public.settings set join_command = ${q("!" + "x".repeat(d.commandMax + 1))} where channel_id = ${q(channel)};
    raise exception 'defaults: a command of % characters saved, DEFAULTS says %', ${d.commandMax + 1}, ${d.commandMax} using errcode = 'XX000';
  exception when check_violation then null;
  end;
${checks}
${retention}
end $$;

select 'defaults ok';
rollback;`);
